version: "3"
services:
  server:
   image: node:18
   volumes:
     - ./:/src
   ports:
     - "3000:3000"
   working_dir: /src
   command: npx docusaurus start --host 0.0.0.0
  web:
   image: httpd
   ports:
     - "8080:80"
  init:
   image: node:18
   profiles: ["init"]
   volumes:
     - ./:/src
   working_dir: /src
   command: npm install  
